### ISSUE TITLE
Url

### ISSUE THREAD

**Issue by robmarkcole** [SFrav/field-delineation-planet#1]
HI
Can you add the url to the paper? A google search did not return it
Thanks

**Comment by SFrav** [comment]
Hi Robin,

You can read about some of my work on field boundary delineation here: https://www.cirrus.ac.uk/casestudies/cirrus_field_boundries_AW_LOW.pdf

This particular repo is a fork from what is now a Planet subsidiary, called Sinergise and their Sentinel Hub platform. More on that purchase here: https://www.planet.com/pulse/planet-acquires-sinergise-business-a-new-chapter-in-earth-observation/ 

An insight into how the result of this particular codebase was incorporated into Planet can be found here: https://developers.planet.com/docs/planetary-variables/field-boundaries/

If you do make use of this workflow I would suggest removing the few lines of code that pickle the reference vector data – it's not used and more than doubles the size of "eo-patches".

What is it that you're trying to weigh up with this codebase?

Simon

**Comment by robmarkcole** [comment]
HI Simon, thanks for sharing these resources. I wanted to read the manuscript "Field boundary delineation benchmarking: algorithms fit for global challenges" but cannot find it online

**Comment by SFrav** [comment]
Ah, yes. I thought you were commenting on a similarly named forked repo. That manuscript has been shelved for now. I've only returned to pick up on this area of research recently. However, there are a few initiatives on field boundary delineation that have some good momentum. There's the CSIRO article and [model code here](https://github.com/feevos/tfcl/tree/master), the EU-JRC/Sinergise AI4boundaries [dataset here](https://github.com/waldnerf/ai4boundaries/tree/main), and the Taylor Geospatial/NASA Harvest FIBOA project on [reference data harmonisation here](https://github.com/fiboa/).
